"""Schema inicial — estado dos modelos em 2026-08-04.

Gerada por autogenerate a partir de models/database.py, cobrindo tudo o que já
existia em produção até aqui: perfis, leads, decisores, atividades, o banco
global de contatos (companies/persons/e-mails/telefones/padrões), créditos,
opt-outs, tokens da extensão, conexões de CRM e a fila de jobs.

Banco criado antes do Alembic entrar não deve rodar esta migração: use
`alembic stamp head` (o init_db() faz isso sozinho ao criar o schema).

Revision ID: 528805047d04
Revises:
Create Date: 2026-08-04
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528805047d04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('linkedin_slug', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.JSON(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('phones', sa.JSON(), nullable=True),
    sa.Column('main_email', sa.String(length=255), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('cnpj_data', sa.JSON(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_linkedin_slug'), ['linkedin_slug'], unique=False)

    op.create_table('crm_connections',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.create_table('email_patterns',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('samples_count', sa.Integer(), nullable=True),
    sa.Column('votes', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('catch_all', sa.Boolean(), nullable=True),
    sa.Column('mx_ok', sa.Boolean(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('extension_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_tokens_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('raw_input_domain', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_confidence', sa.String(length=20), nullable=True),
    sa.Column('mx_provider', sa.String(length=100), nullable=True),
    sa.Column('mx_provider_confidence', sa.String(length=20), nullable=True),
    sa.Column('mx_records', sa.JSON(), nullable=True),
    sa.Column('dns_report', sa.JSON(), nullable=True),
    sa.Column('hosting_provider', sa.String(length=100), nullable=True),
    sa.Column('employee_count', sa.JSON(), nullable=True),
    sa.Column('employee_count_linkedin', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('corporate_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('enrichment_version', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)

    op.create_table('opt_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by_hash', sa.String(length=64), nullable=True),
    sa.Column('pending_value', sa.String(length=320), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opt_outs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opt_outs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opt_outs_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_opt_outs_value_hash'), ['value_hash'], unique=True)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('searches_used', sa.Integer(), nullable=False),
    sa.Column('searches_limit', sa.Integer(), nullable=False),
    sa.Column('reveals_used', sa.Integer(), nullable=False),
    sa.Column('reveals_limit', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_calls_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_calls_provider'), ['provider'], unique=False)

    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    op.create_table('decision_makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title_searched', sa.String(length=255), nullable=True),
    sa.Column('title_found', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('probable_emails', sa.JSON(), nullable=True),
    sa.Column('match_confidence', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_makers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_makers_id'), ['id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_id', ['status', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('linkedin_slug', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=30), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name_raw', sa.String(length=255), nullable=True),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_company_domain'), ['company_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_persons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_linkedin_slug'), ['linkedin_slug'], unique=False)

    op.create_table('person_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'email', name='uq_person_email')
    )
    with op.batch_alter_table('person_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_emails_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_emails_person_id'), ['person_id'], unique=False)

    op.create_table('person_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('e164', sa.String(length=20), nullable=False),
    sa.Column('formatted', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'e164', name='uq_person_phone')
    )
    with op.batch_alter_table('person_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_phones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_phones_person_id'), ['person_id'], unique=False)

    op.create_table('reveals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('credits_charged', sa.Integer(), nullable=True),
    sa.Column('found_email', sa.Boolean(), nullable=True),
    sa.Column('found_phone', sa.Boolean(), nullable=True),
    sa.Column('provider_chain', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reveals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reveals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reveals_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reveals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reveals_user_person', ['user_id', 'person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reveals', schema=None) as batch_op:
        batch_op.drop_index('ix_reveals_user_person')
        batch_op.drop_index(batch_op.f('ix_reveals_user_id'))
        batch_op.drop_index(batch_op.f('ix_reveals_person_id'))
        batch_op.drop_index(batch_op.f('ix_reveals_id'))

    op.drop_table('reveals')
    with op.batch_alter_table('person_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_phones_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_phones_id'))

    op.drop_table('person_phones')
    with op.batch_alter_table('person_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_emails_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_emails_id'))

    op.drop_table('person_emails')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_linkedin_slug'))
        batch_op.drop_index(batch_op.f('ix_persons_id'))
        batch_op.drop_index(batch_op.f('ix_persons_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_persons_company_id'))
        batch_op.drop_index(batch_op.f('ix_persons_company_domain'))

    op.drop_table('persons')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index('ix_jobs_status_id')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_batch_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('decision_makers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_makers_id'))

    op.drop_table('decision_makers')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_lead_id'))
        batch_op.drop_index(batch_op.f('ix_activities_id'))

    op.drop_table('activities')
    op.drop_table('stripe_events')
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_calls_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_calls_id'))

    op.drop_table('provider_calls')
    op.drop_table('profiles')
    with op.batch_alter_table('opt_outs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opt_outs_value_hash'))
        batch_op.drop_index(batch_op.f('ix_opt_outs_token_hash'))
        batch_op.drop_index(batch_op.f('ix_opt_outs_id'))

    op.drop_table('opt_outs')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_domain'))

    op.drop_table('leads')
    with op.batch_alter_table('extension_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_extension_tokens_code'))

    op.drop_table('extension_tokens')
    op.drop_table('email_patterns')
    op.drop_table('crm_connections')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_linkedin_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))
        batch_op.drop_index(batch_op.f('ix_companies_domain'))
        batch_op.drop_index(batch_op.f('ix_companies_cnpj'))

    op.drop_table('companies')
    # ### end Alembic commands ###
